{% set name = "BeAMF" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UVVIS-BIRA-IASB/BeAMF/archive/refs/tags/{{ version }}.tar.gz
  sha256: 763bd0200e70168c85eb120205dbd5a408056958d6f0ae89f6d47d534ce959a7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - beamf = BeAMF:cml

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - netCDF4

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/UVVIS-BIRA-IASB/BeAMF
  summary: 'compute Air Mass Factors (AMF) for trace gas retrievals derived from satellite sensors'
  description: |
    BeAMF serves as a tool designed to compute Air Mass Factors (AMF) for trace gas retrievals
    derived from satellite sensors. It relies on lookup tables (LUT) of altitude-dependent AMF,
    generated through radiative transfer code.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://uvvis-bira-iasb.github.io/BeAMF/
  dev_url: https://github.com/UVVIS-BIRA-IASB/BeAMF

extra:
  recipe-maintainers:
    - svniemeijer
